input_features:
  - 
    preprocessing:
      word_tokenizer: hf_tokenizer
      pretrained_model_name_or_path: distilbert-base-uncased

training:
  batch_size: 16
  early_stop: 5

parameters:
  input_features.name.encoder: distilbert
  output_features.name.fc_layers:
    space: choice
    type: category
    categories: [
      [{fc_size: 512}, {fc_size: 256}],
      [{fc_size: 512}],
      [{fc_size: 256}]
    ]
