input_features:
  - 
    preprocessing:
      word_tokenizer: hf_tokenizer
      pretrained_model_name_or_path: google/electra-base-generator

training:
  batch_size: 16

parameters:
  input_features.name.encoder: electra
  output_features.name.fc_layers:
    space: choice
    type: category
    categories: [
      [{fc_size: 512}, {fc_size: 256}],
      [{fc_size: 512}],
      [{fc_size: 256}]
    ]
